# Generated by Django 4.1.5 on 2023-08-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cloudinaryurls_productt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryurls',
            name='productt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product'),
        ),
    ]
