# Generated by Django 4.1.5 on 2023-09-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cloudinaryurls_productt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryurls',
            name='productt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloudinaryurls_set', to='main.product'),
        ),
    ]
