# Generated by Django 4.1.5 on 2023-12-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(null=True, verbose_name='Facebook link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(null=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(null=True, verbose_name='Linkedin link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='x_twitter',
            field=models.URLField(null=True, verbose_name='X/Twitter link'),
        ),
    ]
