# Generated by Django 4.1.5 on 2023-12-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customuser_facebook_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(default='No link provided', null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(default='No link provided', null=True, verbose_name='Instagram link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(default='No link provided', null=True, verbose_name='Linkedin link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='x_twitter',
            field=models.URLField(default='No link provided', null=True, verbose_name='X/Twitter link'),
        ),
    ]
