# Generated by Django 4.1.5 on 2023-12-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customuser_facebook_alter_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, default='No Facebook link provided', null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, default='No Instagram link provided', null=True, verbose_name='Instagram link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, default='No LinkedIn link provided', null=True, verbose_name='Linkedin link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop_description',
            field=models.TextField(blank=True, default='Welcome...', max_length=1024),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop_url',
            field=models.CharField(blank=True, default='No link yet...', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='x_twitter',
            field=models.URLField(blank=True, default='No X/Twitter link provided', null=True, verbose_name='X/Twitter link'),
        ),
    ]
