# Generated by Django 4.1.5 on 2023-12-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_customuser_facebook_alter_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, default='No Facebook link provided', max_length=200, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, default='No Instagram link provided', max_length=200, null=True, verbose_name='Instagram link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.CharField(blank=True, default='No LinkedIn link provided', max_length=200, null=True, verbose_name='Linkedin link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='x_twitter',
            field=models.CharField(blank=True, default='No X/Twitter link provided', max_length=200, null=True, verbose_name='X/Twitter link'),
        ),
    ]
