# Generated by Django 4.1.5 on 2023-12-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customuser_facebook_alter_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lga',
            field=models.CharField(blank=True, default='Lagos Mainland', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, default='Lagos', max_length=200),
        ),
    ]
